# Generated by Django 3.2.9 on 2021-11-26 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_categoria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=15)),
                ('Correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Habitaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nro_habitacion', models.CharField(default='', max_length=3)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='habitaciones')),
                ('Estado_habitacion', models.CharField(choices=[('1', 'Disponible'), ('2', 'No Disponible')], max_length=2)),
                ('Cerradura_electronica', models.BooleanField(default=True)),
                ('Wifi', models.CharField(choices=[('1', '4G'), ('2', '5G')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_habitacion', models.CharField(max_length=100)),
                ('Cantidad_camas', models.DecimalField(decimal_places=0, max_digits=1)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
                ('Precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_reserva', to='API.cliente')),
                ('Habitacion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_reserva', to='API.habitaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Hoteles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_hotel', models.CharField(max_length=100)),
                ('Ubicacion', models.CharField(max_length=100)),
                ('Calificacion', models.DecimalField(decimal_places=0, max_digits=1)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='hoteles')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria_hoteles', to='API.categorias')),
            ],
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='Hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_habitaciones', to='API.hoteles'),
        ),
        migrations.AddField(
            model_name='habitaciones',
            name='Tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_habitacion_habitaciones', to='API.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Arduinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arduino', models.CharField(max_length=100)),
                ('Temperatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Estado_ventalidor', models.BooleanField(default=True)),
                ('Estado_calefactor', models.BooleanField(default=True)),
                ('Habitacion', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_arduinos', to='API.habitaciones')),
            ],
        ),
    ]
