# Generated by Django 3.2 on 2021-11-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_reserva_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='Token',
        ),
        migrations.AddField(
            model_name='reserva',
            name='Codigo',
            field=models.CharField(default='', max_length=6),
        ),
    ]
